apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: ocpv01
rendezvousIP: 10.220.168.38
AdditionalNTPSources:
  - 22.90.202.30
hosts:
- hostname: master01.ocpv01.ia.stng.cloudcenter.corp 
  role: master
  interfaces:
  - macAddress: 9c:63:c0:f8:11:b6
    name: enP18s18f0np0
  - macAddress: 9c:63:c0:f8:11:b7
    name: enP18s18f1np1
  - macAddress: b8:e9:24:33:5d:1e
    name: enP2s2f0np0
  - macAddress: b8:e9:24:33:5d:1f
    name: enP2s2f1np1
  networkConfig:
    dns-resolver:
      config:
        server:
        - 180.156.253.15
    interfaces:
    - ipv4:
        dhcp: false
        enabled: false
      link-aggregation:
        mode: 802.3ad
        options:
          miimon: '100'
        port:
        - enP18s18f0np0
        - enP2s2f0np0
      name: bond0
      state: up
      type: bond
    - ipv4:
        address:
        - ip: 10.220.168.6
          prefix-length: 27
        dhcp: false
        enabled: true
      name: bond0.2004
      state: up
      type: vlan
      vlan:
        base-iface: bond0
        id: 2004
    - ipv4:
        dhcp: false
        enabled: false
      link-aggregation:
        mode: 802.3ad
        options:
          miimon: '100'
        port:
        - enP18s18f1np1
        - enP2s2f1np1
      name: bond1
      state: up
      type: bond
    - ipv4:
        address:
        - ip: 10.220.168.38
          prefix-length: 27
        dhcp: false
        enabled: true
      name: bond1.2005
      state: up
      type: vlan
      vlan:
        base-iface: bond1
        id: 2005
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 10.220.168.33
        next-hop-interface: bond1.2005
        table-id: 254
      - destination: 10.202.16.0/22
        next-hop-address: 10.220.168.1
        next-hop-interface: bond0.2004
        table-id: 254
      - destination: 22.0.0.0/8
        next-hop-address: 10.220.168.1
        next-hop-interface: bond0.2004
        table-id: 254
  rootDeviceHints:
    deviceName: /dev/nvme4n1
